name: Dummy CI
on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      start-tag:
        description: 'Start tag number'
        required: true
      end-tag:
        description: 'End tag number'
        required: true

jobs:
  validateTrigger:
    if: ${{ !github.event.pull_request.draft && github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Contextual QA Checklists
        uses: wyozi/contextual-qa-checklist-action@1.2
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

  generateChangeLog:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      START_TAG: ${{ github.event.inputs.start-tag }}
      END_TAG: ${{ github.event.inputs.end-tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: "Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: true
          compareLink: true
          futureRelease: v0.0.5
          bugsLabel: "### Bug Fixes 🐛"
          issuesLabel: "### Miscellaneous Issues ✌️"
          sinceTag: ${{ github.event.inputs.start-tag }}
          #dueTag:  ${{ github.event.inputs.end-tag }}
          stripGeneratorNotice: true
          addSections: '{"release":{"prefix":"### Release Issues 🎊","labels":["release"]}, "Others":{"prefix":"### Other Issues ","labels":["others"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for tag
          file_pattern: CHANGELOG.md
      - name: "Fetch Changelog Entry For The Tag"
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: v0.0.5
          path: CHANGELOG.md
      - name: "Release NebulaStream Repository"
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
