name: Dummy CI
on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - opened
      - reopened

jobs:
  validateTrigger:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Contextual QA Checklists
        uses: wyozi/contextual-qa-checklist-action@1.2
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}