name: Dummy CI
on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      start-tag:
        description: 'Start tag number'
        required: true
      end-tag:
        description: 'End tag number'
        required: true

jobs:
  validateTrigger:
    if: ${{ !github.event.pull_request.draft && github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Contextual QA Checklists
        uses: wyozi/contextual-qa-checklist-action@1.2
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

  generateChangeLog:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      START_TAG: ${{ github.event.inputs.start-tag }}
      END_TAG: ${{ github.event.inputs.end-tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: "Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: true
          compareLink: true
          bugsLabel: "## Bug Fixes 🐛"
          since-tag: ${{ github.event.inputs.start-tag }}
          due-tag:  ${{ github.event.inputs.end-tag }}
          addSections: '{"Release Issues 🎊":{"labels":["release"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for tag
          file_pattern: CHANGELOG.md